[Distribution]
Distribution=arch

[Output]
Format=directory
OutputDirectory=/workdir/output
ImageId=subsystem

[Content]
Packages=
    base
    sudo
    dbus
    util-linux
    glibc
    shadow
    bash
    bash-completion
    binutils
    curl
    gcc
    glibc-locales
    jq
    less
    lsof
    man-db
    nano
    openssh
    patchelf
    rsync
    tar
    tree
    udev
    unzip
    usbutils
    wget
    atuin
    fastfetch
    git
    neovim
    starship
    vim

WithRecommends=no
CleanPackageMetadata=yes
