#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

## set errexit, pipefail, errtrace
set -eo pipefail -o errtrace

## do our checks
if [[ "$EUID" == "0" ]] || [[ "$EUID" -lt "1000" ]]; then
    echo "[!!!] Please do not run this as an administrator or system user."
    exit 77
fi

## set constants
UID=$(id -u "$USER")
HASH=$(echo -n "$(cat /etc/machine-id)$USER" | sha256sum | awk '{print $1}')
RTMEDIR="$HOME/.cache/subsystem-$HASH"
readonly UID
readonly HASH
readonly RTMEDIR

## utilities
start-subsystem() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong during startup, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # logging
    echo "[---] Starting subsystem."

    # start container
    echo "[1/2] Starting container."
    podman-cmd

    # set runtime lock
    echo "[2/2] Creating runtime lock."
    mkdir -p "$RTMEDIR"
    touch "$RTMEDIR"/runtime.lock

    # reset traps
    trap - ERR SIGTERM
}

stop-subsystem() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong during shutdown, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # logging
    echo "[---] Stopping subsystem."

    # clear runtime lock
    echo "[1/2] Removing runtime lock."
    rm -rf "$RTMEDIR"

    # stop container
    echo "[2/2] Stopping container."
    podman container stop -it 30 "subsystem-$HASH"

    # reset traps
    trap - ERR SIGTERM
}

podman-cmd() {
    if podman container exists "subsystem-$HASH"; then
        podman container rm -if "subsystem-$HASH"
    fi

    podman container run \
        --rm \
        --init \
        --detach \
        --cgroups=split \
        --name "subsystem-$HASH" \
        --hostname subsystem \
        --log-driver journald \
        --env "SUBSYSTEM_USER=$USER" \
        --network host \
        --user 0:0 \
        --userns keep-id \
        --tmpfs /run \
        --workdir "/home/$USER" \
        -v "$HOME":"/home/$USER":rslave \
        -v /tmp:/tmp:rslave,nosuid,nodev,rbind \
        -v /run/user/"$UID":/run/user/"$UID":ro,rslave \
        -v /usr/lib/subsystem/bin/ignition:/usr/libexec/ignition:ro \
        -v /usr/lib/subsystem/bin/synergy:/usr/bin/synergy:ro \
        --rootfs /var/lib/subsystem/"$HASH"/rootfs \
        /usr/libexec/ignition
}

monitor() (
    # trap SIGTERM
    trap '
        TERM_RECEIVED=true
        if [[ -n "$SLEEP_PID" ]]; then
            kill "$SLEEP_PID" 2>/dev/null
        fi
    ' SIGTERM

    # logging
    echo "[---] Monitoring subsystem-$HASH."

    # set vars
    local SLEEP_PID=""
    local TERM_RECEIVED=false

    # utilities
    isleep() {
        sleep "$1" &
        SLEEP_PID=$!
        wait "$SLEEP_PID" 2>/dev/null
        SLEEP_PID=""
    }

    # monitor and always restart subsystem regardless of shutdown/deletion
    while [[ -f "$RTMEDIR/runtime.lock" ]]; do
        if $TERM_RECEIVED; then break; fi

        while podman ps --filter "name=subsystem-$HASH" --filter "status=running" --format "{{.Names}}" | grep -q "^subsystem-$HASH$"; do
            isleep 1
            if $TERM_RECEIVED; then break 2; fi
        done

        if $TERM_RECEIVED || [[ ! -f "$RTMEDIR/runtime.lock" ]]; then break; fi

        echo "[-i-] subsystem-$HASH exited, restarting..."

        if ! podman-cmd; then
            FAILED=$(( FAILED + 1 ))
            echo "[-!-] Failed to restart subsystem-$HASH, failure counter is at $FAILED."
        else
            isleep 1
            if $TERM_RECEIVED; then break; fi

            if ! podman ps --filter "name=subsystem-$HASH" --filter "status=running" --format "{{.Names}}" | grep -q "^subsystem-$HASH$"; then
                FAILED=$(( FAILED + 1 ))
                echo "[-!-] Failed to start subsystem-$HASH, failure counter is at $FAILED."
            else
                FAILED=0
                echo "[-i-] Restarted subsystem-$HASH successfully."
            fi
        fi

        if [[ "$FAILED" -ge "5" ]]; then
            echo "[!!!] Reached 5 or more consecutive failed restarts."
            exit 1
        fi
    done
)

## main logic
systemd-notify --status "Starting..."
start-subsystem

systemd-notify --ready --status "Monitoring subsystem-$HASH."
monitor

systemd-notify --status "Stopping..."
stop-subsystem

systemd-notify --status "Stopped."
