#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

## set pipefail
set -o pipefail

## do our checks
if [[ "$EUID" != "0" ]]; then
    echo "[!!!] Please run this as an administrator."
    exit 77
fi

## set arrays
declare -a operational_users

## utilities
mount-rootfs() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong while mounting, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # clean checkout destination to ensure checkout accuracy
    if [[ -d "$REPODIR" ]]; then
        echo "[-i-] Cleaning previous checkout."
        rm -rf "$REPODIR"
    fi

    # checkout commit
    echo "[1/2] Checking out rootfs."
    ostree --repo="$REPODIR/../repo" checkout -H "subsystem-rootfs-$TARGETUSR" "$REPODIR"

    # lock repodir from runtime modification
    echo "[2/2] Mounting rootfs."
    mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,bind "$REPODIR" "$REPODIR"

    # reset traps
    trap - ERR SIGTERM
}

umount-rootfs() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong while unmounting, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    if [[ ! -d "$REPODIR" ]]; then
        echo "[-!-] Target repository $REPODIR does not exist, ignoring."
        return
    fi

    # unmount rootfs
    echo "[1/2] Umounting rootfs."
    if findmnt "$REPODIR" >/dev/null; then
        umount -q "$REPODIR"
    else
        echo "[-!-] Rootfs unmounted already, ignoring."
    fi

    # cleanup
    echo "[2/2] Cleaning rootfs checkout."
    rm -rf "$REPODIR"

    # reset traps
    trap - ERR SIGTERM
}

start-mounts() {
    # logging
    echo "[---] Mounting subsystem rootfs for all users."

    # mount subsystem rootfs for all current users
    awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd | while read -r TARGETUSR; do
        if [[ ${operational_users[*]} =~ ${TARGETUSR} ]]; then
            echo "[-i-] Already mounted for user $TARGETUSR."
            continue
        else
            echo "[-i-] Mounting rootfs for user $TARGETUSR."
            operational_users+=("$TARGETUSR")
        fi

        HASH=$(echo -n "$(cat /etc/machine-id)$TARGETUSR" | sha256sum | awk '{print $1}')
        REPODIR="/var/lib/subsystem/$HASH"
        USER_SUBUID_START=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f2)
        USER_SUBGID_START=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f2)
        USER_SUBUID_RANGE=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f3)
        USER_SUBGID_RANGE=$(grep "^$TARGETUSR:" /etc/subgid | cut -d: -f3)

        if [[ -z $USER_SUBUID_START || -z $USER_SUBGID_START || -z $USER_SUBUID_RANGE || -z $USER_SUBGID_RANGE ]]; then
            echo "[!!!] User $TARGETUSR has improperly configured sub{uid,gid}s, skipping."
            continue
        fi

        if ! mount-rootfs; then
            echo "[-!-] Mount process failed for user $TARGETUSR."
        fi

        unset HASH REPODIR USER_SUBUID_START USER_SUBGID_START USER_SUBUID_RANGE USER_SUBGID_RANGE
    done

    # logging
    echo "[---] Subsystem rootfs mounting done."
}

stop-mounts() {
    # logging
    echo "[---] Mounting subsystem rootfs for all users."

    # umount subsystem rootfs for all current users
    for TARGETUSR in "${operational_users[@]}"; do
        echo "[-i-] Unmounting rootfs for user $TARGETUSR."

        HASH=$(echo -n "$(cat /etc/machine-id)$TARGETUSR" | sha256sum | awk '{print $1}')
        REPODIR="/var/lib/subsystem/$HASH"

        if ! umount-rootfs; then
            echo "[!!!] Unmount process failed for user $TARGETUSR."
        fi

        unset HASH REPODIR
    done

    # logging
    echo "[---] Subsystem rootfs unmounting done."
}

monitor() {
    # trap SIGTERM
    trap 'kill "$NOTIFY_PID" 2>/dev/null; break' SIGTERM

    # logging
    echo "[---] Monitoring for new users."

    # monitor new users and mount for them
    while true; do
        inotifywait -m -e close_write /etc/passwd &
        local NOTIFY_PID=$!

        wait $NOTIFY_PID 2>/dev/null
        
        if [[ ! -d "/proc/$NOTIFY_PID" && "$NOTIFY_PID" -ne 0 ]]; then
            break
        fi

        echo "[-i-] New user detected, refreshing rootfs mounts."
        start-mounts
    done

    # logging
    echo "[---] Beginning shutdown."

    # reset trap
    trap - SIGTERM
}

init() {
    # logging
    echo "[---] Checking for initialization."

    # set constants
    local RSTRING=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)
    readonly RSTRING

    # initialize ostree repo and commit rootfs if needed
    if [[ ! -f "/var/lib/subsystem/.initialized" ]]; then
        echo "[1/5] Preparing for initialization."
        rm -rf /var/lib/subsystem/repo
        mkdir -p /var/lib/subsystem/repo

        echo "[2/5] Initializing rootfs repository."
        ostree --repo="/var/lib/subsystem/repo" init --mode=bare

        echo "[3/5] Mounting base rootfs."
        mkdir -p /tmp/subsystem-"$RSTRING"
        mount -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk /tmp/subsystem-"$RSTRING"

        echo "[4/5] Commiting base rootfs to repository."
        ostree --repo="/var/lib/subsystem/repo" commit --branch="subsystem-rootfs-base" --subject="base subsystem rootfs snapshot" /tmp/subsystem-"$RSTRING"

        echo "[5/5] Finalizing."
        umount -q /tmp/subsystem-"$RSTRING"
        rm -rf /tmp/subsystem-"$RSTRING"
        touch /var/lib/subsystem/.initialized
    fi

    # logging
    echo "[---] Initialized."
}

## main logic
systemd-notify --status "Initializing..."
init

systemd-notify --status "Starting..."
start-mounts

systemd-notify --ready --status "Monitoring for new users."
monitor

systemd-notify --status "Stopping..."
stop-mounts

systemd-notify --status "Stopped."