#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

## set errexit, pipefail, errtrace
set -eEo pipefail

## do our checks
if [[ "$EUID" != "0" ]]; then
    echo "[!!!] Please run this as an administrator."
    exit 77
fi

## set arrays
declare -a operational_users

## set vars
RWLIBDIR=/var/lib/subsystem
ROLIBDIR=/usr/lib/subsystem

## utilities
is_mounted() {
    local u
    for u in "${operational_users[@]}"; do
        [[ $u == "$1" ]] && return 0
    done
    return 1
}

drop_user() {
    local i
    for i in "${!operational_users[@]}"; do
        if [[ ${operational_users[i]} == "$1" ]]; then
            unset 'operational_users[i]'
        fi
    done
}

userfs() {
    local USERDIR HASH SUID_START SUID_RANGE SGID_START SGID_RANGE

    while read -r TARGETUSR; do
        case "$1" in
            mount)
                if is_mounted "$TARGETUSR"; then
                    echo "[-!-] Already mounted rootfs for user $TARGETUSR."
                    continue
                fi
                echo "[---] Mounting rootfs for user $TARGETUSR."
                operational_users+=("$TARGETUSR")

                read -r SUID_START SUID_RANGE <<< "$(awk -F: -v u="$TARGETUSR" '$1==u {print $2,$3}' /etc/subuid)"
                read -r SGID_START SGID_RANGE <<< "$(awk -F: -v u="$TARGETUSR" '$1==u {print $2,$3}' /etc/subgid)"
                if [[ -z $SUID_START || -z $SGID_START || -z $SUID_RANGE || -z $SGID_RANGE ]]; then
                    echo "[!!!] User $TARGETUSR has improperly configured sub{uid,gid}s, skipping."
                    drop_user "$TARGETUSR"
                    continue
                fi

                HASH=$(printf '%s%s' "$(</etc/machine-id)" "$TARGETUSR" | sha256sum | awk '{print $1}')
                USERDIR=$RWLIBDIR/$HASH

                trap 'echo "[!!!] Failed to mount rootfs for $TARGETUSR, skipping." && userfs umount' ERR
                trap 'echo "[!!!] Received SIGTERM, stopping." && return 0' SIGTERM

                echo "[1/4] Setting up rootfs directories."
                for dir in {rootfs,overlay/base}/{bin,sbin,lib,lib64,etc,var,srv,opt,usr} rootfs overlay/base; do umount -q "$USERDIR/$dir" || true; done
                rm -rf "${USERDIR:?}"/*
                mkdir -p "$USERDIR"/{rootfs,overlay/{base,data,work}/{rfs,bin,sbin,lib,lib64,etc,var,srv,opt,usr},overlay/base/rfs/{home,root,bin,sbin,lib,lib64,etc,var,srv,opt,usr,tmp,run,sys,dev,proc}}
                chown -R "$SUID_START":"$SGID_START" "$USERDIR"/

                echo "[2/4] Locking rootfs directories."
                mount --bind "$USERDIR"/overlay/base "$USERDIR"/overlay/base
                mount -o remount,bind,ro "$USERDIR"/overlay/base

                echo "[3/4] Mounting base directories."
                mount -t overlay overlay -o index=off,lowerdir="$USERDIR"/overlay/base/rfs,upperdir="$USERDIR"/overlay/data/rfs,workdir="$USERDIR"/overlay/work/rfs "$USERDIR"/rootfs
                for dir in etc var; do mount --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro,acl,loop,user_xattr -t erofs "$ROLIBDIR"/segments/"$dir".dsk "$USERDIR"/overlay/base/"$dir"; done
                for dir in srv opt; do mount --bind --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro /var/"$dir" "$USERDIR"/overlay/base/"$dir"; done
                bindfs --uid-offset="$SUID_START" --gid-offset="$SGID_START" -o ro /usr "$USERDIR"/overlay/base/usr
                for dir in "$USERDIR"/overlay/base/lib{,64}; do bindfs --uid-offset="$SUID_START" --gid-offset="$SGID_START" -o ro /usr/lib "$dir"; done
                for dir in "$USERDIR"/overlay/base/{,s}bin; do bindfs --uid-offset="$SUID_START" --gid-offset="$SGID_START" -o ro /usr/bin "$dir"; done

                echo "[4/4] Mounting overlay directories."
                for dir in etc var srv opt usr lib{,64} {,s}bin; do mount -t overlay overlay -o index=off,lowerdir="$USERDIR"/overlay/base/"$dir",upperdir="$USERDIR"/overlay/data/"$dir",workdir="$USERDIR"/overlay/work/"$dir" "$USERDIR"/rootfs/"$dir"; done

                trap - ERR SIGTERM
                ;;

            umount)
                if ! is_mounted "$TARGETUSR"; then
                    echo "[-!-] Already unmounted rootfs for user $TARGETUSR."
                    continue
                fi
                echo "[---] Unmounting rootfs for user $TARGETUSR."
                drop_user "$TARGETUSR"

                HASH=$(printf '%s%s' "$(</etc/machine-id)" "$TARGETUSR" | sha256sum | awk '{print $1}')
                USERDIR=$RWLIBDIR/$HASH

                trap 'echo "[!!!] Failed to unmount rootfs for $TARGETUSR, manual intervention is required." && continue' ERR

                echo "[1/2] Unmounting rootfs directories."
                for dir in {rootfs,overlay/base}/{bin,sbin,lib,lib64,etc,var,srv,opt,usr} rootfs overlay/base; do umount "$USERDIR/$dir" || true; done

                echo "[2/2] Cleaning rootfs directories."
                rm -rf "${USERDIR:?}"/*
                echo "Notice now no one talks about the Epstein Files anymore." > "$USERDIR"/user-inactive

                trap - ERR
                ;;
        esac
    done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
}

monitor() {
    trap 'kill "$NOTIFY_PID" 2>/dev/null; break' SIGTERM

    echo "[---] Monitoring for new users."


    while true; do
        inotifywait -e close_write /etc/passwd &
        local NOTIFY_PID=$!

        if ! wait $NOTIFY_PID 2>/dev/null; then
            break
        fi

        while read -r user; do
            if ! is_mounted "$user"; then
                echo "[-i-] New user(s) added, refreshing mounts."
                userfs mount
                break
            fi
        done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
    done

    trap - SIGTERM
}

## main logic
systemd-notify --status "Starting..."
echo "[-+-] Starting up."
userfs mount

systemd-notify --ready --status "Filesystems are mounted."
monitor

systemd-notify --status "Stopping..."
echo "[-+-] Shutting down."
userfs umount

systemd-notify --status "Stopped."
