[Distribution]
Distribution=alpine
Release=edge

[Output]
Format=directory
OutputDirectory=/workdir/output
ImageId=subsystem

[Content]
Packages=
    alpine-base
    doas
    dbus
    util-linux
    musl
    shadow
    bash
    bash-completion
    binutils
    curl
    gcc
    musl-locales
    jq
    less
    lsof
    man-db
    mandoc
    nano
    openssh
    patchelf
    rsync
    tar
    tree
    unzip
    wget
    git
    neovim
    vim
    openrc

WithRecommends=no
CleanPackageMetadata=yes
