# base image
FROM archlinux:latest

# load build files
COPY build_files/subsystem /ctx/

# run main build scripts
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    sh /ctx/00-base.sh && \
    sh /ctx/01-pkgs.sh && \
    sh /ctx/02-extra.sh

# clean up build scripts
RUN rm -rf /ctx
