#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

# this script contains tasks started on subsystem startup
# changes will be applied once you log out and then back in

### BEGIN USER CONFIGURATION

# example: install a package (requires internet connection on host system)
# pacman -S npm

### END USER CONFIGURATION

# configure fastest arch repos
reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist >/dev/null 2>&1 || true
pacman -Sy >/dev/null 2>&1 || true

# set up sudo for the user
if [[ ! -f /etc/sudoers.d/nopasswd-for-subsystem ]]; then
    echo "$SUBSYSTEM_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/nopasswd-for-subsystem
fi

# keep subsystem alive
sleep infinity
