#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

# this script contains tasks performed on subsystem startup
# changes will be applied once your subsystem is restarted, e.g. logging out and back in

### -----BEGIN USER CONFIGURATION-----

# example:
# touch /etc/i-am-working

### -----END USER CONFIGURATION-----

# configure fastest arch repos and update databases
reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist >/dev/null 2>&1 || true
pacman -Sy >/dev/null 2>&1 || true

# set up sudo for the user
if [[ ! -f /etc/sudoers.d/nopasswd-for-subsystem ]]; then
    echo "$SUBSYSTEM_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/nopasswd-for-subsystem
fi

# keep subsystem alive
sleep infinity
