# add Inter font to initramfs
install_items+=" /usr/share/fonts/inter-static/InterStatic-Regular.ttf "
install_items+=" /usr/share/fonts/inter-static/InterStatic-Black.ttf "
install_items+=" /etc/fonts/fonts.conf /etc/fonts/conf.d/ "
install_items+=" /var/cache/fontconfig "