FROM archlinux:latest AS base

COPY system_files /
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

RUN --mount=type=bind,src=build_files/scripts,dst=/build \
    --mount=type=bind,src=build_files/scripts/conf/04-mkosi-bld,dst=/mkosi/mkosi.conf \
    --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/07-finalize.sh

RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=base,src=/,target=/chunkah,ro \
    chunkah build --skip-special-files --max-layers 128 --prune /ostree --prune /sysroot/ostree --output oci:/src/out

FROM oci:out
