FROM archlinux:latest AS base

COPY system_files /
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

RUN --mount=type=bind,src=build_files/scripts,dst=/build \
    --mount=type=bind,src=build_files/config,dst=/config \
    --mount=type=bind,src=build_files/config/04-mkosi-bld,dst=/mkosi/mkosi.conf \
    --mount=type=secret,id=secureboot_cert,required=true \
    --mount=type=secret,id=module_key,required=true \
    --mount=type=secret,id=module_cert,required=true \
    --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-modsign.sh && \
    bash /build/07-finalize.sh

RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

FROM base AS split-kernel
RUN mkdir -p /kernel && \
    bootc container split-kernel-and-rootfs --rootfs / --output /kernel

FROM split-kernel AS rechunk-base
RUN kver=$(ls /kernel) && \
    mkdir -p "/usr/share/split-kernel/$kver/" && \
    cp "/kernel/$kver/vmlinuz" "/usr/share/split-kernel/$kver/" && \
    rm -rf /kernel

FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=rechunk-base,src=/,target=/chunkah,ro \
    chunkah build --skip-special-files --max-layers 128 --prune /ostree --prune /sysroot/ostree --output oci:/src/out
