# !! NOTICE !!
# If a "storage.conf.bk" file is present in the same directory as this file,
# that means your storage configuration was overridden.
# If the file is not present, ignore the rest of this comment.
# Otherwise, please merge this storage configuration with your configuration,
# as this configuration is needed for the containerized shell to work properly.

[storage]
driver = "overlay"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
additionalimagestores = [
    "/var/lib/subsystem/PLACEHOLDER/store"
]