#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

set -e

[[ "$EUID" != "0" ]] && echo "Please run this as an administrator." && exit 1
[[ -z "$1" ]] && echo "Please provide a UID to enter the subsystem as." && exit 1

if [[ -f /etc/subsystem/.entry-lock ]]; then
    echo "Subsystem is starting."
    echo "Please wait, this will not take long."
    while [[ -f /etc/subsystem/.entry-lock ]]; do 
        sleep 0.1
    done
fi

echo "Entering subsystem."
machinectl shell -q subsys@.host /usr/bin/podman exec -u "$1" -it subsystem /bin/fish