#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

# WAHHHHH
set -eo pipefail

# remove fedora remote if present
if flatpak remote-list --system | awk '{print $1}' | grep -qx "fedora"; then
    mapfile -t REFS < <(flatpak list --system --columns=application,origin \
        | awk -v r="fedora" '$2 == r {print $1}')

    if [ "${#REFS[@]}" -gt 0 ]; then
        for ref in "${REFS[@]}"; do
            echo "Uninstalling $ref..."
            flatpak uninstall --system -y --force-remove "$ref"
        done
    fi

    flatpak remote-delete --system --force "fedora"
fi

# create mount dir
mkdir -p /tmp/sysapps

# mount repo if needed
if ! findmnt /tmp/sysapps >/dev/null; then
    mount -o ro,loop /usr/lib/flatpak-sysapps/flatpak-sysapps.dsk /tmp/sysapps
fi

# setup repositories
flatpak remote-add --system --if-not-exists flathub /usr/lib/flatpak-sysapps/flathub.flatpakrepo

# set gtk styling overrides
flatpak override --system --filesystem=xdg-config/gtk-3.0 --filesystem=xdg-config/gtk-4.0

# install system apps
flatpak install --sideload-repo=/tmp/sysapps --system -y flathub $(</etc/.sysapps.list)

# cleanup
umount /tmp/sysapps
rm -f /etc/.sysapps.list
