#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

# do not list users by default
ECHO_USER=0

# check if we aren't root or no arg was provided
if [[ "$EUID" != "0" ]]; then
    echo "[!!!] Please run this as an administrator."
    exit 77
fi

# check if we need to list users
if [[ "$1" == "--list" ]]; then
    ECHO_USER=1
fi

# iterate through every user with a homedir in /var/home
for user in /var/home/*; do
    username=$(basename "$user")
    
    # skip if user doesn't exist
    getent passwd "$username" >/dev/null 2>&1 || continue
    
    # skip if UID < 1000
    user_uid=$(id -u "$username")
    [[ $user_uid -lt 1000 ]] && continue
    
    # execute as or echo user based on flag
    if [[ "$ECHO_USER" == "1" ]]; then
        echo "$username"
    else
        echo "Executing '$1' as $username, uid $user_uid"
        su - "$username" -c "$1"
    fi
done