#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

ECHO_USER=0

[[ "$EUID" != "0" ]] && echo "We are not root, abort!!" && exit 1

if [[ -z "$1" ]]; then
    echo "Usage: $0 'command to run'"
    exit 1
elif [[ "$1" == "--list" ]]; then
    ECHO_USER=1
fi

for user in /var/home/*; do
    username=$(basename "$user")
    if getent passwd "$username" >/dev/null 2>&1; then
        user_uid=$(id -u "$username")
        if [[ $user_uid -ge 1000 ]]; then
            if [[ "$ECHO_USER" != "1" ]]; then
                echo "Executing '$1' as $username, uid $user_uid"
                su - "$username" -c "$1"
            else
                echo "$username"
            fi
        fi
    fi
done