#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

set -e

# constants
readonly MAIN_STORE="/var/lib/subsystem"
MACHINEID="$(cat /etc/machine-id)"
readonly MACHINEID

# utilities
checkmnt() {
    if [[ "$1" == "-n" ]]; then
        ! findmnt "$2" > /dev/null
    else
        findmnt "$1" > /dev/null
    fi
}

cre_conf_file() {
    local home="$1"
    local user
    user="$(basename "$home")"

    cat > "$home/.config/containers/storage.conf" <<EOF
# !! NOTICE !!
# If a "storage.conf.bk" file is present in the same directory as this file,
# that means your storage configuration was overridden.
# If the file is not present, ignore the rest of this comment.
# Otherwise, please merge this storage configuration with your configuration,
# as this configuration is needed for the containerized shell to work properly.

[storage]
driver = "overlay"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
additionalimagestores = [
    "/var/lib/subsystem/$user/store"
]
EOF
    chown "$user":"$user" "$home/.config/containers/storage.conf"
}

# check if we aren't root
if [[ "$EUID" != "0" ]]; then
    echo "Please run this as an administrator."
    exit 1
fi

# chkeck if the main store exists
if [[ ! -d "$MAIN_STORE" ]]; then
    mkdir -p "$MAIN_STORE"
fi

# iterate through args
case "$1" in
    setup-configs)
        for user in $(/usr/libexec/run-as-all-human-users --list); do
            home="/var/home/$user"
            conf_dir="$home/.config/containers"
            marker="$home/.config/.subsystem-store-setup-done-do-not-remove"
            quadlet="$conf_dir/systemd/subsystem-$MACHINEID.container"
            
            if [[ ! -f "$marker" ]]; then # setup storage config if needed
                echo "Creating storage config for $user."
                [[ -f "$conf_dir/storage.conf" ]] && mv "$conf_dir/storage.conf" "$conf_dir/storage.conf.bk"
                mkdir -p "$conf_dir"
                cre_conf_file "$home"
                touch "$marker"
                return
            elif [[ ! -f "$quadlet" ]]; then # setup quadlet config if needed
                echo "Creating quadlet config for $user."
                mkdir -p "$conf_dir/systemd"
                cp -f /etc/subsystem/subsystem.container "$quadlet"
                chown -R "$user":"$user" "$conf_dir/systemd"
                return
            else
                echo "Configs already setup for user $user."
            fi
        done
        ;;
        
    setup-stores)
        for user in $(/usr/libexec/run-as-all-human-users --list); do
            msdir="$MAIN_STORE/$user"
            user_uid=$(id -u "$user")
            user_gid=$(id -g "$user")
            
            # check if msdir already exists; if not, create it
            if [[ -d "$msdir" ]]; then
                echo "Subsystem store already setup for user $user."
            else
                mkdir -p "$msdir"/{store,store-data,.base,.work}
                chown -R "$user_uid":"$user_gid" "$msdir"
                chmod 700 "$msdir"
            fi
        done
        ;;
        
    mount-stores)
        for user in $(/usr/libexec/run-as-all-human-users --list); do
            msdir="$MAIN_STORE/$user"
            user_uid=$(id -u "$user")
            user_gid=$(id -g "$user")

            checkmnt -n "$msdir/.base" && mount --map-users 0:"$user_uid":1 --map-groups 0:"$user_gid":1 --bind /usr/lib/subsystem-store "$msdir/.base" || true # mount base store if not mounted
            checkmnt -n "$msdir/store" && mount -t overlay overlay -o index=off,lowerdir="$msdir"/.base,upperdir="$msdir"/store-data,workdir="$msdir"/.work "$msdir/store" || true # mount store if not mounted
        done
        ;;
        
    unmount-stores)
        echo "Unmounting subsystem image stores."
        for user in $(/usr/libexec/run-as-all-human-users --list); do
            msdir="$MAIN_STORE/$user"

            checkmnt "$msdir/store" && umount "$msdir/store" || true # unmount store if mounted
            checkmnt "$msdir/.base" && umount "$msdir/.base" || true # unmount base store if mounted
        done
        ;;
        
    *)
        echo "Subsystem store management utility 1.0.2"
        echo "Usage: $0 setup-configs|setup-stores|mount-stores|unmount-stores"
        echo "Note: This utility is not intended for use by users."
        exit 1
        ;;
esac
