#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

[[ "$EUID" == "0" ]] && echo "We are root, abort!!" && exit 1

readonly STORE="$HOME/.local/share/subsystem-store"

set -e

cre_conf_file() {
    cat > "$HOME"/.config/containers/storage.conf <<EOF
# !! NOTICE !!
# If a "storage.conf.bk" file is present in the same directory as this file,
# that means your storage configuration was overridden,
# If the file is not present, ignore the rest of this comment.
# If the former is true, please merge this storage configuration with your configuration,
# as this configuration is needed for the containerized shell to work properly.

[storage]
driver = "overlay"

[storage.options]
additionalimagestores = [
    "$STORE/store"
]
EOF
}

mkdir -p "$STORE"/{store,data,.base,.work}

if [[ ! -f "$HOME"/.config/.subsystem-store-setup-done-do-not-remove ]]; then
    if [[ ! -f "$HOME"/.config/containers/storage.conf ]]; then
        mkdir -p "$HOME"/.config/containers/
        cre_conf_file
        touch "$HOME"/.config/.subsystem-store-setup-done-do-not-remove
    else
        mv "$HOME"/.config/containers/storage.conf "$HOME"/.config/containers/storage.conf.bk
        cre_conf_file
        touch "$HOME"/.config/.subsystem-store-setup-done-do-not-remove
    fi
fi

case $1 in
    mount)
        ! findmnt "$STORE"/.base > /dev/null && squashfuse -o uid="$(id -u)",gid="$(id -g)" /usr/lib/subsystem-store/store.dsk "$STORE"/.base || true
        ! findmnt "$STORE"/store > /dev/null && fuse-overlayfs -o lowerdir="$STORE"/.base,upperdir="$STORE"/data,workdir="$STORE"/.work "$STORE"/store || true
        ;;
    umount)
        findmnt "$STORE"/store > /dev/null && fusermount3 -u "$STORE"/store || true
        findmnt "$STORE"/.base > /dev/null && fusermount3 -u "$STORE"/.base || true
        ;;
    *)
        echo "Usage: $0 mount|umount"
        exit 1
        ;;
esac
