#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only

# LOVE MEEEE
set -eo pipefail

# create necessary dirs
mkdir -p /etc/tartaria

# create hash file
hash_file=$(mktemp)

# generate pass
mokutil --generate-hash="tartaria" > "${hash_file}"

# enroll secureboot cert if exists
if [[ -f "/usr/share/tartaria/certs/secureboot.der" ]]; then
    mokutil --import "/usr/share/tartaria/certs/secureboot.der" --hash-file "${hash_file}"
fi

# enroll modules cert if exists
if [[ -f "/usr/share/tartaria/certs/modules.der" ]]; then
    mokutil --import "/usr/share/tartaria/certs/modules.der" --hash-file "${hash_file}"
fi

# cleanup
rm -f "${hash_file}"
touch /etc/tartaria/mok-enrolled
