#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

# love meeeeeeee
set -eo pipefail

# trap EXIT
trap 'echo "[!!!] Something went wrong."' EXIT

# check if we aren't root
if [[ "$EUID" != "0" ]]; then
    echo "[!!!] Please run this as an administrator."
    exit 77
fi

# pull and mount image
echo "[1/3] Fetching dotfile repository."
podman pull ghcr.io/tartaria-dev/cherries:latest -q
MNT=$(podman image mount ghcr.io/tartaria-dev/cherries:latest)

# copy over files
echo "[2/3] Syncing fetched copy of repository with local copy."
mkdir -p /var/lib/cherries
rsync -avH --delete "$MNT"/system_files/ /var/lib/cherries/

# cleanup
echo "[3/3] Cleaning up."
podman image unmount ghcr.io/tartaria-dev/cherries:latest
