[Distribution]
Distribution=arch

[Output]
Format=directory
OutputDirectory=/workdir/output
ImageId=rootfs

[Content]
Bootable=no
Packages=
    base
    sudo
    dbus
    util-linux
    glibc
    shadow
    bash
    bash-completion
    binutils
    curl
    fish
    gcc
    glibc-locales
    jq
    less
    lsof
    man-db
    nano
    openssh
    patchelf
    rsync
    reflector
    tar
    tree
    udev
    unzip
    usbutils
    wget
    atuin
    cava
    fastfetch
    git
    neovim
    starship
    vim
    which
