[Distribution]
Distribution=arch

[Output]
Format=tar
OutputDirectory=/workdir
ImageId=subsystem

[Content]
Packages=
    archlinux-keyring
    atuin
    bash
    bash-completion
    binutils
    bzip2
    coreutils
    curl
    fastfetch
    file
    filesystem
    findutils
    fish
    gawk
    gcc
    gcc-libs
    gettext
    git
    glibc
    glibc-locales
    grep
    gzip
    iproute2
    jq
    less
    licenses
    lsof
    man-db
    nano
    neovim
    openssh
    pacman
    patchelf
    procps-ng
    psmisc
    rsync
    sed
    shadow
    starship
    sudo
    tar
    tree
    unzip
    util-linux
    vim
    wget
    xz

WithRecommends=no
CleanPackageMetadata=yes