#!/usr/bin/env bash
# thank your Zirconium devs for this fix :vlone:

GSHADOW_FILE="/etc/gshadow"
GROUP_FILE="/etc/group"

for f in $(cat $GROUP_FILE); do
   cut -f1 -d':' <(echo $f) | xargs -I{} grep ^"{}" $GSHADOW_FILE &>/dev/null || \
     echo $(cut -f1 -d':' <(echo $f)):'!*::' >> $GSHADOW_FILE
done
