#!/bin/bash

[[ "$EUID" != "0" ]] && echo "We are not root, abort!!" && exit 1

if [[ -z "$1" ]]; then
    echo "Usage: $0 'command to run'"
    exit 1
fi

for user in /var/home/*; do
    username=$(basename "$user")
    if getent passwd "$username" >/dev/null 2>&1; then
        user_uid=$(id -u "$username")
        if [[ $user_uid -ge 1000 ]]; then
            echo "Executing '$1' as $username, uid $user_uid"
            su - "$username" -c "$1"
        fi
    fi
done