#!/bin/bash

# if not root, exit
[[ "$EUID" -ne 0 ]] && echo "Not root, abort." && exit 1

set -e

if ! id "subsys" >/dev/null 2>&1; then
    # create subsys user
    groupadd -rg 767 subsys
    useradd -rmd /etc/subsystem-conf -u 767 -g 767 subsys

    # calculate and assign sub{uid,gid} range for subsys user
    next_uid=$(awk -F: '{print $2 + $3}' /etc/subuid 2>/dev/null | sort -n | tail -1)
    next_gid=$(awk -F: '{print $2 + $3}' /etc/subgid 2>/dev/null | sort -n | tail -1)
    usermod --add-subuids ${next_uid:-100000}-$((${next_uid:-100000}+65535)) --add-subgids ${next_gid:-100000}-$((${next_gid:-100000}+65535)) subsys

    # enable linger for subsys user
    loginctl enable-linger subsys
fi

case $1 in
    poweron)
        # create rootfs dirs if they don't already exist
        echo "Preparing."
        mkdir -p /var/lib/subsystem/{,rootfs,.rootfs-work}
        chown -R 767:767 /var/lib/subsystem/
        chmod -R 744 /var/lib/subsystem/

        # ensure subsystem service is generated
        systemctl --user -M subsys@.host daemon-reload

        # setup subsystem root
        echo "Mounting subsystem rootfs."
        ! findmnt /usr/lib/subsystem/rootfs > /dev/null && mount -t erofs -o loop,ro,acl,user_xattr /usr/lib/subsystem/subsystem.dsk /usr/lib/subsystem/rootfs
        ! findmnt /subsys > /dev/null && mount -t overlay overlay -o index=off,metacopy=off,lowerdir=/usr/lib/subsystem/rootfs,upperdir=/var/lib/subsystem/rootfs,workdir=/var/lib/subsystem/.rootfs-work /subsys
        ! findmnt /subsys/home > /dev/null && mount -o bind /var/home /subsys/home

        # start subsystem container
        echo "Starting subsystem."
        systemctl --user -M subsys@.host start subsystem.service
        
        # ensure all human users on the host exist in subsystem
        echo "Creating users."
        for user in /var/home/*; do
            username=$(basename "$user")
            user_uid=$(id -u "$user")
            user_gid=$(id -g "$user")

            if getent passwd "$username" >/dev/null 2>&1; then
                if [[ $user_uid -ge 1000 ]]; then
                    if ! chroot /subsys getent passwd "$username" >/dev/null 2>&1; then
                        chroot /subsys groupadd -g "$user_gid" "$username"
                        chroot /subsys useradd -md "/home/$username" -u "$user_uid" -g "$user_gid" "$username"
                        echo "Created user $username, uid $user_uid, gid $user_gid"
                    fi
                fi
            fi
        done
        ;;
    poweroff)
        # power off subsystem container
        echo "Stopping subsystem."
        systemctl --user -M subsys@.host stop subsystem.service

        # unmount subsystem rootfs (if mounted)
        echo "Unmounting subsystem rootfs."
        findmnt /subsys/home > /dev/null && umount /subsys/home
        findmnt /subsys > /dev/null && umount /subsys
        findmnt /usr/lib/subsystem/rootfs > /dev/null && umount /usr/lib/subsystem/rootfs
        ;;
    enter-subsystem-as)
        shift

        # check if an arg was passed
        [[ -z "$1" ]] && echo "Usage: $0 enter-subsystem-as <username>" && exit 1

        # disallow logging in as root
        [[ "$1" == "root" ]] && echo "Cannot log in as root." && exit 1

        # open shell in subsystem as provided user
        echo "Opening shell."
        machinectl shell -q subsys@.host /usr/bin/podman exec -u $1 -it subsystem /bin/bash
        ;;
    *)
        echo "Usage: $0 poweron|poweroff|enter-subsystem-as <username>"
        exit 1
        ;;
esac
