#!/bin/bash

[[ "$EUID" != "0" ]] && echo "We are not root, abort!!" && exit 1

set -e

mkdir -p /var/lib/subsystem

for user in /var/home/*; do
    username=$(basename "$user")
    if getent passwd "$username" >/dev/null 2>&1; then
        user_uid=$(id -u "$username")
        if [[ $user_uid -ge 1000 ]]; then
            if [[ ! -d /var/lib/subsystem/$username ]]; then
                echo "Creating store for $username."
                mkdir -p /var/lib/subsystem/$username
                chown "$username":"$username" /var/lib/subsystem/$username
                chmod 700 /var/lib/subsystem/$username
            fi
        fi
    fi
done