#!/bin/bash

# if not root, exit
[[ "$EUID" -ne 0 ]] && echo "Not root, abort." && exit 1

# create subsystem user if it doesn't exist
if ! id "subsys" >/dev/null 2>&1; then
    useradd -rmd /etc/subsystem-conf -s /bin/bash subsys
    chown -R subsys:subsys /etc/subsystem-conf
    loginctl enable-linger subsys
fi

case $1 in
    poweron)
        # create rootfs dirs if they don't already exist
        mkdir -p /var/lib/subsystem/{,rootfs,.rootfs-work}

        # make sure subsystem service is generated
        machinectl shell subsys@.host /usr/bin/systemctl --user daemon-reload

        # setup subsystem root
        mount -t erofs -o loop,ro,acl,user_xattr /usr/lib/subsystem/subsystem.dsk /usr/lib/subsystem/rootfs
        mount -t overlay overlay -o index=off,metacopy=off,lowerdir=/usr/lib/subsystem/rootfs,upperdir=/var/lib/subsystem/rootfs,workdir=/var/lib/subsystem/.rootfs-work /subsys
        mount -o bind /var/home /subsys/home

        # start subsystem container
        machinectl shell subsys@.host /usr/bin/systemctl --user start subsystem.service
        ;;
    poweroff)
        # power off subsystem container
        machinectl shell subsys@.host /usr/bin/systemctl --user stop subsystem.service

        # unmount subsystem rootfs
        umount /subsys/home
        umount /subsys
        umount /usr/lib/subsystem/rootfs
        ;;
    *)
        echo "Usage: $0 poweron|poweroff"
        exit 1
        ;;
esac
