#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the Tartaria project:
#    https://github.com/tartaria-dev/tartaria
#
# Copyright (C) 2026 Tartaria Developers
#
# Tartaria is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# Tartaria is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tartaria; if not, see <http://www.gnu.org/licenses/>.

[[ "$EUID" != "0" ]] && echo "We are not root, abort!!" && exit 1

set -e

mkdir -p /var/lib/subsystem

for user in /var/home/*; do
    username=$(basename "$user")
    if getent passwd "$username" >/dev/null 2>&1; then
        user_uid=$(id -u "$username")
        if [[ $user_uid -ge 1000 ]]; then
            if [[ ! -d /var/lib/subsystem/$username ]]; then
                echo "Creating store for $username."
                mkdir -p /var/lib/subsystem/$username
                chown "$username":"$username" /var/lib/subsystem/$username
                chmod 700 /var/lib/subsystem/$username
            fi
        fi
    fi
done