#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

# LOVE MEEEEEE
set -eo pipefail

# sync config files
cp -a /usr/share/greeter-defaults/config.toml /etc/greetd/config.toml
cp -a /usr/share/greeter-defaults/sync.toml /var/lib/noctalia-greeter/sync.toml
