# base image
FROM docker.io/cachyos/cachyos-v3:latest AS final

# copy over system files
COPY system_files/mainsys /
COPY system_files/subsys /mkosi/mkosi.extra/

# fetch Brew and Cherries
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

# import build args
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

# run main build scripts
RUN --mount=type=bind,src=build_files/mainsys,dst=/build \
    --mount=type=bind,src=build_files/subsys,dst=/mkosi \
    --mount=type=bind,src=system_files/subsys,dst=/mkosi/mkosi.extra \
    --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/07-finalize.sh

# clean then lint image
RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=final,src=/,target=/chunkah,ro \
    chunkah build --skip-special-files --max-layers 128 --output oci:/src/out

# finalize
FROM oci:out
