# base image
FROM archlinux:latest AS final

# copy over build files
COPY build_files/mainsys /build/
COPY build_files/subsys /mkosi/

# copy over system files
COPY system_files/mainsys /
COPY system_files/subsys /mkosi/mkosi.extra/

# fetch Brew and Cherries
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

# import build args
ARG SYSTEMD_OFFLINE
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

# run main build scripts
RUN --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-finalize.sh

# clean then lint image
RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
ARG CACHEBUST=1
RUN --mount=from=final,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
    chunkah build --skip-special-files --max-layers 128 --output oci-archive:/run/src/out.ociarchive

# finalize
FROM oci-archive:out.ociarchive
