# base image
FROM archlinux:latest AS base

# copy over system files
COPY system_files /

# fetch Brew and Cherries
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

# import build args
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

# run main build scripts
RUN --mount=type=bind,src=build_files/system,dst=/build \
    --mount=type=bind,src=build_files/system/conf/04-mkosi-bld,dst=/mkosi/mkosi.conf \
    --mount=type=secret,id=secureboot_cert,required=true \
    --mount=type=secret,id=module_key,required=true \
    --mount=type=secret,id=module_cert,required=true \
    --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-modsign.sh && \
    bash /build/07-finalize.sh

# clean then lint image
RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

# split the kernel/initramfs from the signed rootfs
FROM base AS split-kernel
RUN mkdir -p /kernel && \
    bootc container split-kernel-and-rootfs --rootfs / --output /kernel

# copy kernel to /usr/share/split-kernel, required for ISO builds
FROM split-kernel AS rechunk-base
RUN kver=$(ls /kernel) && \
    mkdir -p "/usr/share/split-kernel/$kver/" && \
    cp "/kernel/$kver/vmlinuz" "/usr/share/split-kernel/$kver/" && \
    rm -rf /kernel

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=rechunk-base,src=/,target=/chunkah,ro \
    chunkah build --skip-special-files --max-layers 128 --prune /ostree --prune /sysroot/ostree --output oci:/src/out

# use rechunked output as new base
FROM oci:out AS base-chunked

# build signed, sealed UKI
FROM base AS sealed-uki
RUN --mount=type=bind,src=build_files/system,dst=/build \
    --mount=type=bind,from=base-chunked,target=/target \
    --mount=type=bind,from=split-kernel,source=/kernel,target=/kernel \
    --mount=type=secret,id=secureboot_key,required=true \
    --mount=type=secret,id=secureboot_cert,required=true \
    bash /build/08-ukify.sh

# add UKI + shim chain to base
FROM base-chunked AS final
COPY --from=sealed-uki /out/*.efi /boot/EFI/Linux/
COPY --from=sealed-uki /out/grubx64.efi /boot/EFI/BOOT/grubx64.efi
COPY --from=base /usr/share/shim-signed/shimx64.efi /boot/EFI/BOOT/BOOTX64.EFI
COPY --from=base /usr/share/shim-signed/mmx64.efi /boot/EFI/BOOT/mmx64.efi
