# base image
FROM docker.io/cachyos/cachyos-v3:latest AS base

# copy over system files
COPY system_files/mainsys /
COPY system_files/subsys /mkosi/mkosi.extra/

# fetch Brew and Cherries
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

# import build args
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

# run main build scripts
RUN --mount=type=bind,src=build_files/mainsys,dst=/build \
    --mount=type=bind,src=build_files/subsys,dst=/mkosi \
    --mount=type=bind,src=system_files/subsys,dst=/mkosi/mkosi.extra \
    --mount=type=secret,id=module_key,required=true \
    --mount=type=secret,id=module_cert,required=true \
    --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-modsign.sh && \
    bash /build/07-finalize.sh

# clean then lint image
RUN rm -rf /tmp/* /tmp/.* /run/* && \
    bootc container lint --fatal-warnings

# split the kernel/initramfs from the signed rootfs
FROM base AS split
RUN mkdir -p /kernel && \
    bootc container split-kernel-and-rootfs --rootfs / --output /kernel

# build signed, sealed UKI
FROM base AS sealed
RUN --mount=type=bind,src=build_files/mainsys,dst=/build \
    --mount=type=bind,from=split,target=/target \
    --mount=type=bind,from=split,source=/kernel,target=/kernel \
    --mount=type=secret,id=secureboot_key,required=true \
    --mount=type=secret,id=secureboot_cert,required=true \
    bash /build/08-ukify.sh

# add UKI + shim chain to base
FROM split AS final
COPY --from=sealed /out/*.efi /boot/EFI/Linux/
COPY --from=sealed /out/grubx64.efi /boot/EFI/BOOT/grubx64.efi
COPY --from=sealed /out/secureboot.der /usr/share/tartaria/certs/secureboot.der
COPY --from=base /usr/share/shim-signed/shimx64.efi /boot/EFI/BOOT/BOOTX64.EFI
COPY --from=base /usr/share/shim-signed/mmx64.efi /boot/EFI/BOOT/mmx64.efi

# move artifacts out of /kernel
RUN kver=$(ls /kernel) && \
    mkdir -p "/usr/share/split-kernel/$kver/" && \
    cp "/kernel/$kver/vmlinuz" "/usr/share/split-kernel/$kver/" && \
    rm -rf /kernel

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=final,src=/,target=/chunkah,ro \
    chunkah build --skip-special-files --max-layers 128 --output oci:/src/out

# finalize
FROM oci:out
