# base image
FROM archlinux:latest AS final

# copy over build files
COPY build_files/mainsys /build/
COPY build_files/subsys /mkosi/

# copy over system files
COPY system_files/mainsys /
COPY system_files/subsys /mkosi/mkosi.extra/
COPY sysapps /

# fetch Brew, Cherries (our lovely dotfiles), and our AUR pkgs
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/
COPY --from=ghcr.io/tartaria-dev/branches:latest / /packages/

# import build args
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT
ARG BUILD_IS_PR

# run main build scripts
RUN --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-finalize.sh

# lint image
RUN bootc container lint

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=final,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build \
            --skip-special-files \
            --max-layers 128 > /run/src/out.ociarchive

# finalize
FROM oci-archive:out.ociarchive
ENTRYPOINT ["git"]
