# base image
FROM archlinux:latest AS base

# copy over build files
COPY build_files/mainsys /build/
COPY build_files/subsys /mkosi/

# copy over system files
COPY system_files/mainsys /
COPY system_files/subsys /mkosi/mkosi.extra/

# fetch Brew and Cherries
COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
COPY --from=ghcr.io/tartaria-dev/cherries:latest / /usr/share/tartaria/cherries/

# import build args
ARG IMAGE_FLAVOR
ARG IMAGE_VARIANT

# run main build scripts
RUN --mount=type=tmpfs,dst=/tmp \
    bash /build/00-base.sh && \
    bash /build/01-packages.sh && \
    bash /build/02-sysapps.sh && \
    bash /build/03-subsystem.sh && \
    bash /build/04-systemd.sh && \
    bash /build/05-extras.sh && \
    bash /build/06-finalize.sh

# lint image
RUN bootc container lint --fatal-warnings

# split the kernel/initramfs
FROM base AS split
RUN mkdir -p /kernel && bootc container split-kernel-and-rootfs --rootfs / --output /kernel

# build signed, sealed UKI
FROM base AS sealed-uki
RUN pacman -S --noconfirm --needed systemd-ukify sbsigntools
RUN --mount=type=bind,src=build_files/mainsys,dst=/build \
    --mount=type=bind,from=split,target=/target \
    --mount=type=bind,from=split,source=/kernel,target=/kernel \
    --mount=type=secret,id=secureboot_key,required=false \
    --mount=type=secret,id=secureboot_cert,required=false \
    bash /build/07-ukify.sh

# add UKI to base
FROM split AS final
COPY --from=sealed-uki /out/*.efi /boot/EFI/Linux/

# rechunk image
FROM quay.io/coreos/chunkah AS chunkah
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=final,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build \
            --skip-special-files \
            --max-layers 128 > /run/src/out.ociarchive

# finalize
FROM oci-archive:out.ociarchive
ENTRYPOINT ["git"]
