#!/bin/bash

[[ "$(whoami)" != "subsystem" ]] && echo "This command is running under the incorrect user. Press 'CTRL+C' to exit." && sleep infinity

set -oue pipefail

if [[ ! -z "$(distrobox ls | grep subsystem)" ]]; then
    exec distrobox enter subsystem
else
    if pgrep -f "/usr/libexec/init-subsystem" > /dev/null; then
        echo "Subsystem is initializing, please wait..."
        wait '$(pgrep -f "/usr/libexec/init-subsystem")'
        if [[ -z "$(distrobox ls | grep subsystem)" ]]; then
            echo "Subsystem failed to initialize! Opening debug shell."
            exec sh
        else
            echo "Subsystem initialized. Entering subsystem..."
            exec distrobox enter subsystem
        fi
    else
        echo "An unknown error occured. Starting debug shell."
        exec sh
    fi
fi
