#!/bin/bash

[[ "$(whoami)" != "subsystem" ]] && echo "This command is running under the incorrect user. Press 'CTRL+C' to exit." && sleep infinity

set -oue pipefail

if [[ -z "$(distrobox ls | grep subsystem)" ]]; then
    podman load -i /usr/share/subsystem/subsystem.container
    distrobox create -i ghcr.io/tartaria-dev/subsystem:latest --name subsystem
else
    echo "Subsystem has already been created."
    exit 0
fi