#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

## set pipefail, errtrace
set -o pipefail -o errtrace

## do our checks
if [[ "$EUID" != "0" ]]; then
    echo "[!!!] Please run this as an administrator."
    exit 77
fi

## set arrays
declare -a operational_users

## utilities
mount-rootfs() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong while mounting, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # clean checkout destination to ensure checkout accuracy
    echo "[1/4] Preparing rootfs directiories."
    rm -rf "$REPODIR"/checkout
    mkdir -p "$REPODIR"/{rootfs,overlay/{data,work}}
    chown "$USER_SUBUID_START":"$USER_SUBGID_START" "$REPODIR"/rootfs

    # checkout commit
    echo "[2/4] Checking out rootfs."
    ostree --repo="$REPODIR/../repo" checkout -H "subsystem-rootfs-base" "$REPODIR"/checkout

    # lock repodir from runtime modification
    echo "[3/4] Locking rootfs checkout."
    mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,bind "$REPODIR"/checkout "$REPODIR"/checkout

    # mount overlayfs
    echo "[4/4] Mounting rootfs overlay."
    mount -t overlay overlay -o index=off,lowerdir="$REPODIR"/checkout,upperdir="$REPODIR"/overlay/data,workdir="$REPODIR"/overlay/work "$REPODIR"/rootfs

    # reset traps
    trap - ERR SIGTERM
}

umount-rootfs() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong while unmounting, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    if [[ ! -d "$REPODIR" ]]; then
        echo "[-!-] Target repository $REPODIR does not exist, ignoring."
        return
    fi

    # unmount rootfs
    echo "[1/3] Umounting rootfs overlay."
    if findmnt "$REPODIR"/rootfs >/dev/null; then
        umount -q "$REPODIR"/rootfs
    else
        echo "[-!-] Rootfs unmounted already, ignoring."
    fi

    # unlock rootfs
    echo "[2/3] Unlocking rootfs checkout."
    if findmnt "$REPODIR"/checkout >/dev/null; then
        umount -q "$REPODIR"/checkout
    else
        echo "[-!-] Rootfs unlocked already, ignoring."
    fi

    # cleanup
    echo "[3/3] Cleaning rootfs checkout."
    rm -rf "$REPODIR"/checkout

    # reset traps
    trap - ERR SIGTERM
}

start-mounts() {
    # logging
    echo "[---] Mounting subsystem rootfs for all users."

    # mount subsystem rootfs for all current users
    while read -r TARGETUSR; do
        if [[ ${operational_users[*]} =~ ${TARGETUSR} ]]; then
            echo "[-i-] Already mounted for user $TARGETUSR."
            continue
        else
            echo "[-i-] Mounting rootfs for user $TARGETUSR."
            operational_users+=("$TARGETUSR")
        fi

        HASH=$(echo -n "$(cat /etc/machine-id)$TARGETUSR" | sha256sum | awk '{print $1}')
        REPODIR="/var/lib/subsystem/$HASH"
        USER_SUBUID_START=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f2)
        USER_SUBGID_START=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f2)
        USER_SUBUID_RANGE=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f3)
        USER_SUBGID_RANGE=$(grep "^$TARGETUSR:" /etc/subgid | cut -d: -f3)

        if [[ -z $USER_SUBUID_START || -z $USER_SUBGID_START || -z $USER_SUBUID_RANGE || -z $USER_SUBGID_RANGE ]]; then
            echo "[!!!] User $TARGETUSR has improperly configured sub{uid,gid}s, skipping."
            for i in "${!operational_users[@]}"; do
                if [[ "${operational_users[i]}" == "$TARGETUSR" ]]; then
                    unset 'operational_users[i]'
                fi
            done
            continue
        fi

        if ! mount-rootfs; then
            echo "[-!-] Mount process failed for user $TARGETUSR."
        fi

        unset HASH REPODIR USER_SUBUID_START USER_SUBGID_START USER_SUBUID_RANGE USER_SUBGID_RANGE
    done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
}

stop-mounts() {
    # logging
    echo "[---] Unounting subsystem rootfs for all users."

    # umount subsystem rootfs for all current users
    while read -r TARGETUSR; do
        if [[ ! ${operational_users[*]} =~ ${TARGETUSR} ]]; then
            echo "[-i-] Already unmounted for user $TARGETUSR."
            continue
        else
            echo "[-i-] Unmounting rootfs for user $TARGETUSR."
            for i in "${!operational_users[@]}"; do
                if [[ "${operational_users[i]}" == "$TARGETUSR" ]]; then
                    unset 'operational_users[i]'
                fi
            done
        fi

        HASH=$(echo -n "$(cat /etc/machine-id)$TARGETUSR" | sha256sum | awk '{print $1}')
        REPODIR="/var/lib/subsystem/$HASH"

        if ! umount-rootfs; then
            echo "[!!!] Unmount process failed for user $TARGETUSR."
        fi

        unset HASH REPODIR
    done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
}

monitor() {
    # trap SIGTERM
    trap 'kill "$NOTIFY_PID" 2>/dev/null; break' SIGTERM

    # logging
    echo "[---] Monitoring for new users."

    # monitor new users and mount for them
    while true; do
        inotifywait -e close_write /etc/passwd &
        local NOTIFY_PID=$!

        if ! wait $NOTIFY_PID 2>/dev/null; then
            break
        fi

        while read -r user; do
            if [[ ! " ${operational_users[*]} " =~ [[:space:]]${user}[[:space:]] ]]; then
                echo "[-i-] New user(s) added, refreshing mounts."
                start-mounts
                break
            fi
        done < <(grep -vE "root|nobody|[^0-9][0-9]{1,3}[^0-9]|^[0-9]{1,3}$|^[0-9]{1,3}[^0-9]|[^0-9][0-9]{1,3}$" /etc/passwd | awk -F: '{print $1}')
    done

    # logging
    echo "[---] Beginning shutdown."

    # reset trap
    trap - SIGTERM
}

init() {
    # logging
    echo "[---] Initializing."

    # initialize ostree repo and commit rootfs if needed
    if [[ ! -f "/var/lib/subsystem/.initialized" ]]; then
        echo "[1/5] Preparing for initialization."
        rm -rf /var/lib/subsystem/repo
        mkdir -p /var/lib/subsystem/repo

        echo "[2/5] Initializing rootfs repository."
        ostree --repo="/var/lib/subsystem/repo" init --mode=bare

        echo "[3/5] Mounting base rootfs."
        mkdir -p /tmp/subsystem-base-setup
        mount -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk /tmp/subsystem-base-setup

        echo "[4/5] Commiting base rootfs to repository."
        ostree --repo="/var/lib/subsystem/repo" commit --branch="subsystem-rootfs-base" --subject="base subsystem rootfs snapshot" /tmp/subsystem-base-setup

        echo "[5/5] Finalizing."
        umount -q /tmp/subsystem-base-setup
        rm -rf /tmp/subsystem-base-setup
        touch /var/lib/subsystem/.initialized
    fi
}

## main logic
systemd-notify --status "Initializing..."
init

systemd-notify --status "Starting..."
start-mounts

systemd-notify --ready --status "Monitoring for new users."
monitor

systemd-notify --status "Stopping..."
stop-mounts

systemd-notify --status "Stopped."