#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

## set errexit, pipefail, errtrace
set -eo pipefail -o errtrace

## do our checks
if [[ "$EUID" == "0" ]] || [[ "$EUID" -lt "1000" ]]; then
    echo "[!!!] Please do not run this as an administrator or system user."
    exit 77
fi

## set constants
HASH=$(echo -n "$(cat /etc/machine-id)$USER" | sha256sum | awk '{print $1}')
RTMEDIR="$HOME/.cache/subsystem-$HASH"
readonly HASH
readonly RTMEDIR

## utilities
start-subsystem() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong during startup, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # check if filesystemd is still starting; if so, wait
    if [[ "$(systemctl --user is-failed subsystem-filesystemd)" == "activating" ]]; then
        echo "[-i-] subsystem-filesystemd has not finished startup, waiting."

        while [[ "$(systemctl --user is-failed subsystem-filesystemd)" == "activating" ]]; do
            sleep 1
        done
        
        if [[ "$(systemctl --user is-failed subsystem-filesystemd)" != "active" ]]; then
            echo "[!!!] subsystem-filesystemd has failed to start."
        fi
    fi

    # logging
    echo "[---] Starting subsystem."

    # start container
    echo "[1/2] Starting container."
    podman-cmd

    # set runtime lock
    echo "[2/2] Creating runtime lock."
    mkdir -p "$RTMEDIR"
    touch "$RTMEDIR"/runtime.lock

    # reset traps
    trap - ERR SIGTERM
}

stop-subsystem() {
    # trap ERR, SIGTERM
    trap 'echo "[!!!] Something went wrong during shutdown, aborting." && return 1' ERR
    trap 'echo "[!!!] Received SIGTERM, aborting." && return 0' SIGTERM

    # logging
    echo "[---] Stopping subsystem."

    # clear runtime lock
    echo "[1/2] Removing runtime lock."
    rm -rf "$RTMEDIR"

    # stop container
    echo "[2/2] Stopping container."
    podman container stop -it 30 "subsystem-$HASH"
    podman container rm -if "subsystem-$HASH"

    # reset traps
    trap - ERR SIGTERM
}

monitor() (
    # block if subsystem is running
    if podman ps --filter "name=subsystem-$HASH" --filter "status=running" --format "{{.Names}}" | grep -q "^subsystem-$HASH$"; then
        podman wait "subsystem-$HASH" &
        local WAIT_PID=$!
        wait "$WAIT_PID"
        echo "[-i-] Subsystem exited with code $?."
    fi
)

podman-cmd() {
    # remove container if it exists
    if podman container exists "subsystem-$HASH"; then
        podman container rm -if "subsystem-$HASH"
    fi

    # create and start container
    podman container run \
        --init \
        --detach \
        --cgroups=split \
        --restart=always \
        --name "subsystem-$HASH" \
        --hostname subsystem \
        --log-driver journald \
        --env "SUBSYSTEM_USER=$USER" \
        --network host \
        --user 0:0 \
        --userns keep-id \
        --tmpfs /run \
        --workdir "/home/$USER" \
        -v "$HOME":"/home/$USER":rslave \
        -v /tmp:/tmp:rslave,nosuid,nodev,rbind \
        -v /run/user/"$UID":/run/user/"$UID":ro,rslave \
        -v /usr/lib/subsystem/bin/ignition:/usr/libexec/ignition:ro \
        -v /usr/lib/subsystem/bin/synergy:/usr/bin/synergy:ro \
        --rootfs /var/lib/subsystem/"$HASH"/rootfs \
        /usr/libexec/ignition
}

## main logic
systemd-notify --status "Starting..."
start-subsystem

systemd-notify --ready --status "Subsystem is running."
monitor

systemd-notify --status "Stopping..."
stop-subsystem

systemd-notify --status "Stopped."
