---
name: Build Tartaria ISOs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 */3 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-stable
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs for Tartaria (stable-${{ matrix.IMAGE_FLAVOR }})
    runs-on: ubuntu-26.04
    permissions:
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_FLAVOR: arch-berbere
          - IMAGE_FLAVOR: arch-amchoor
          - IMAGE_FLAVOR: arch-mahleb
          - IMAGE_FLAVOR: arch-saffron
          - IMAGE_FLAVOR: cachy-berbere
          - IMAGE_FLAVOR: cachy-amchoor
          - IMAGE_FLAVOR: cachy-mahleb
          - IMAGE_FLAVOR: cachy-saffron
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Prepare environment
        run: |
          # Lowercase the image uri
          echo "IMAGE_REGISTRY=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}" >> "${GITHUB_ENV}"

      - name: Remove unecessary software
        uses: hastd/free-disk-space@v0.1.2

      - name: Build ISO
        uses: tartaria-dev/iso-builder@main
        with:
          container-image: 'ghcr.io/tartaria-dev/tartaria:stable-${{ matrix.IMAGE_FLAVOR }}'
          iso-path: './iso'
          iso-name: 'tartaria-${{ matrix.IMAGE_FLAVOR }}'

      - name: Install Oras
        uses: oras-project/setup-oras@v2

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push to GHCR
        run: |
          oras push "${IMAGE_REGISTRY}/tartaria-iso:${{ matrix.IMAGE_FLAVOR }}" \
            --artifact-type application/vnd.tartaria.iso.v1 \
            "./iso/tartaria-${{ matrix.IMAGE_FLAVOR }}.iso:application/octet-stream"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign ISO
        run: |
          cosign sign --yes \
            "${IMAGE_REGISTRY}/tartaria-iso:${{ matrix.IMAGE_FLAVOR }}"